---
title: "biwhitening SPMF"
author: "DongyueXie"
date: "2023-06-05"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Biwhitening EBNMF + smooth priors.

```{r}
library(funflash)
library(flashier)
ploter2 = function(EF,main=NULL){
  p = nrow(EF)
  library(ggplot2)
  library(tidyr)
  library(tidyverse)
  library(dplyr)
  # Convert the matrix EF to a data frame and gather the columns
  EF_df <- as.data.frame(EF) %>%
    mutate(row_number = 1:n()) %>%
    pivot_longer(cols = -row_number, names_to = "column", values_to = "value")

  # Create the ggplot2 plot
  pp <- ggplot(EF_df, aes(x = row_number, y = value)) +
    geom_line(color = 2, size = 1) +
    facet_wrap(~column, ncol = 1, scales = "free_y") +
    labs(x = "", y = "") +
    theme_minimal() +
    theme(
      strip.text = element_blank(),
      strip.background = element_blank(),
      axis.text.y = element_blank()  # Remove y-axis numbers
    )+
    ggtitle(main)

  # Print the plot
  print(pp)
  pp
}

K = 2
n=45
p=256
# l0 = 0.1
# l1 = 1
# L = cbind(c(rep(l1,n/3),rep(l0,n/3*2)),
#           c(rep(l0,n/3),rep(l1,n/3),rep(l0,n/3)),
#           c(rep(l0,n/3*2),rep(l1,n/3)))

f0 = 0.5

FF = matrix(f0, nrow=p, ncol=3)
f1 = 10
f2 = 5
FF[(p/8*1):(p/8*2),1] = f1
FF[(p/8*3):(p/8*4),2] = f2
FF[(p/8*5):(p/8*7),3] = f1

FF2 = matrix(f0, nrow=p, ncol=3)
FF2[(p/8*1):(p/8*2),1] = f2
FF2[(p/8*3+10):(p/8*4-10),2] = f1
FF2[(p/8*5):(p/8*7),3] = f2

FFF = cbind(c(FF[,1],FF2[,3]),c(FF[,2],FF2[,2]),c(FF[,3],FF2[,1]))
FFFn = exp(log(FFF)+matrix(rnorm(nrow(FFF)*ncol(FFF),0,0.1),nrow=nrow(FFF)))

set.seed(12345)

L = matrix(0,nrow=n,ncol=K)
pi0=1/3
while(sum(rowSums(L)==0)>0){
  for(k in 1:K){
    l1 = c(rexp(n*pi0,10),
           rexp(n*(1-pi0)/2,5),
           rexp(n*(1-pi0)/2,1))
    L[,k] =  l1[sample(1:n)]
  }
}

y = matrix(rpois(n*p*2,tcrossprod(L,FFF[,1:K])),nrow=n)
#fit.nmf = fastTopics::fit_poisson_nmf(y,k=K)
#temp = poisson_to_multinom(fit.nmf$F,fit.nmf$L)
#ploter2(temp$FF,main=NULL)

#fit.stm5 = ebpmf_identity(y,K=K)
#ploter2(fit.stm5$EF,main=NULL)

bw = biwhitening(y)
S = (1/tcrossprod(bw$u,bw$v))

fit_bw_smoothing <- flash.init(y,var.type = c(1,2),S=S) %>%
  flash.add.greedy(Kmax=10,
                   maxiter=100,
                   ebnm.fn = c(ebnm::ebnm_point_exponential, ebpmf::ebnm_ndwt),
                   init.fn = function(f) init.fn.default(f, dim.signs = c(1, 1))
  )%>%
  flash.backfit() %>%
  flash.nullcheck()

plot(fit_bw_smoothing$F.pm[,1],type='l')
plot(fit_bw_smoothing$F.pm[,2],type='l')

sldf = ldf(fit_bw_smoothing)
p1= ploter2(sldf$F,main="Biwhitening EBNMF + smooth factors (unconstrained)")

fit_bw_pe <- flash.init(y,var.type = c(1,2),S=S) %>%
  flash.add.greedy(Kmax=10,
                   maxiter=100,
                   ebnm.fn = c(ebnm::ebnm_point_exponential, ebnm::ebnm_point_exponential),
                   init.fn = function(f) init.fn.default(f, dim.signs = c(1, 1))
  )%>%
  flash.backfit() %>%
  flash.nullcheck()

sldf_pe = ldf(fit_bw_pe)
p2=ploter2(sldf_pe$F[,1:K],main="Biwhitening EBNMF")

#plot(fit_bw_smoothing$F.pm[,3],type='l')

#fit_bw_smoothing$elbo

# 
L_true_scaled = poisson_to_multinom(FFF[,1:K],L)
p3=ploter2(L_true_scaled$FF,main="True factors")
library(gridExtra)
p_all = grid.arrange(p3,p1,p2)
```


```{r}

set.seed(2023)
f0 = 0.5
FF = matrix(f0, nrow=p, ncol=3)
f1 = 5
f2 = 1
FF[(p/8*1):(p/8*2),1] = f1
FF[(p/8*3):(p/8*4),2] = f2
FF[(p/8*5):(p/8*7),3] = f1

FF2 = matrix(f0, nrow=p, ncol=3)
FF2[(p/8*1):(p/8*2),1] = f2
FF2[(p/8*3+10):(p/8*4-10),2] = f1
FF2[(p/8*5):(p/8*7),3] = f2

FFF = cbind(c(FF[,1],FF2[,3]),c(FF[,2],FF2[,2]),c(FF[,3],FF2[,1]))
FFFn = exp(log(FFF)+matrix(rnorm(nrow(FFF)*ncol(FFF),0,0.1),nrow=nrow(FFF)))

L = matrix(0,nrow=n,ncol=K)
pi0=1/3
while(sum(rowSums(L)==0)>0){
  for(k in 1:K){
    l1 = c(rexp(n*pi0,10),
           rexp(n*(1-pi0)/2,5),
           rexp(n*(1-pi0)/2,1))
    L[,k] =  l1[sample(1:n)]
  }
}

y = matrix(rpois(n*p*2,tcrossprod(L,FFF[,1:K])),nrow=n)

y = y[-which(rowSums(y)<10),]

bw = biwhitening(y)
S = (1/tcrossprod(bw$u,bw$v))

fit_bw_smoothing <- flash.init(y,var.type = c(1,2),S=S) %>%
  flash.add.greedy(Kmax=10,
                   maxiter=100,
                   ebnm.fn = c(ebnm::ebnm_point_exponential, ebpmf::ebnm_dwt_haar),
                   init.fn = function(f) init.fn.default(f, dim.signs = c(1, 1))
  )%>%
  flash.backfit() %>%
  flash.nullcheck()

plot(fit_bw_smoothing$F.pm[,1],type='l')
plot(fit_bw_smoothing$F.pm[,2],type='l')

sldf = ldf(fit_bw_smoothing)
p1= ploter2(sldf$F,main="Biwhitening EBNMF + smooth factors (unconstrained)")

fit_bw_pe <- flash.init(y,var.type = c(1,2),S=S) %>%
  flash.add.greedy(Kmax=10,
                   maxiter=100,
                   ebnm.fn = c(ebnm::ebnm_point_exponential, ebnm::ebnm_point_exponential),
                   init.fn = function(f) init.fn.default(f, dim.signs = c(1, 1))
  )%>%
  flash.backfit() %>%
  flash.nullcheck()

sldf_pe = ldf(fit_bw_pe)
p2=ploter2(sldf_pe$F[,1:K],main="Biwhitening EBNMF")

#plot(fit_bw_smoothing$F.pm[,3],type='l')

#fit_bw_smoothing$elbo

# 
L_true_scaled = poisson_to_multinom(FFF[,1:K],L)
p3=ploter2(L_true_scaled$FF,main="True factors")
library(gridExtra)
p_all = grid.arrange(p3,p1,p2)
```

