---
title: "compare sgom and stm on gene srsf3"
author: "DongyueXie"
date: "2023-05-06"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


## sgom fit

The method was due to Xing, and the method is initialized using kmeans

```{r,fig.width=9,fig.height=12}
K = 5
fit_cluster_mix = readRDS('output/sgom_srsf3.rds')
par(mfrow=c(5,1))
for(k in 1:K){
  plot(fit_cluster_mix$phi[k,],type='l')
}
```



## stm fit, fasttopics init

I used fasttopics for initialization, and I ran it 6 times.

```{r,fig.width=9,fig.height=12}
par(mfrow=c(5,1))
for(i in 0:5){
  fit=readRDS(paste('output/ebpmf_srsf3_run',i,'.rds'))
  print(fit$fit_ebpmf$elbo)
  for(k in 1:K){
  plot(fit$fit_ebpmf$EF_smooth[,k],type='l')
}
}
```

## stm fit, kmeans init

```{r,fig.width=9,fig.height=12}
fit_ebpmf_kmeans = readRDS('output/ebpmf_srsf3_kmeans_init.rds')
par(mfrow=c(5,1))
for(k in 1:K){
  plot(fit_ebpmf_kmeans$EF_smooth[,k],type='l')
}
```

## stm fit, sgom init

```{r,fig.width=9,fig.height=12}
fit_ebpmf_sgom_init = readRDS('output/ebpmf_srsf3_sgom_init.rds')
par(mfrow=c(5,1))
for(k in 1:K){
  plot(fit_ebpmf_sgom_init$EF_smooth[,k],type='l')
}
```

## fasttopics fit

```{r,fig.width=9,fig.height=12}
par(mfrow=c(5,1))
for(i in 0:5){
  fit=readRDS(paste('output/ebpmf_srsf3_run',i,'.rds'))
  for(k in 1:K){
  plot(fit$init$F[,k],type='l')
}
}
```

## kmeans fit

```{r,fig.width=9,fig.height=12}
init = readRDS('output/kmeans_srsf3.rds')
par(mfrow=c(5,1))
for(k in 1:K){
  plot(init$centers[k,],type='l')
}
```


## Code

```{r,eval=F}
datax = read.csv('/project2/mstephens/cfbuenabadn/SRSF3.Counts.csv.gz')
rownames(datax)=datax[,1]
datax[1:5,1:5]
datax = datax[,-1]
dim(datax)
datax = as.matrix(datax)

library(smashr)
library(ebpmf)
library(Matrix)

# source('https://github.com/DongyueXie/ebpmf/blob/master/void/cluster_mix.R')
K = 5
fit_cluster_mix = cluster.mix(datax,K=5,tol=1e-3,maxit=50,smooth = T)
saveRDS(fit_cluster_mix,file='output/sgom_srsf3.rds')
#init = kmeans(datax,5,nstart = 5)
datax = Matrix(datax,sparse=T)
set.seed(12345)
for(i in 1:5){
  init = fastTopics::fit_poisson_nmf(datax,k=K,init.method = 'random')
  fit_ebpmf = ebpmf_identity(datax,K=5,tol = 1e-3,maxiter = 100,init = list(L_init = init$L,F_init = init$F))
  saveRDS(list(init=init,fit_ebpmf=fit_ebpmf),file=paste('output/ebpmf_srsf3_run',i,'.rds'))
}

fit_ebpmf_kmeans = ebpmf_identity(datax,K=5,tol = 1e-3,maxiter = 100,init = 'kmeans')
saveRDS(fit_ebpmf_kmeans,file='output/ebpmf_srsf3_kmeans_init.rds')

L_init = fit_cluster_mix$pi
F_init = t(fit_cluster_mix$phi)
L_init = L_init*rowSums(datax)
ratio = adjLF(L_init,F_init)
L_init = ratio$L_init
F_init = ratio$F_init
fit_ebpmf_sgom_init = ebpmf_identity(datax,K=5,tol = 1e-3,maxiter = 100,init = list(L_init = L_init,F_init = F_init))
saveRDS(fit_ebpmf_sgom_init,file='output/ebpmf_srsf3_sgom_init.rds')

par(mfrow=c(5,1))
for(k in 1:K){
  plot(init$F[,k],type='l')
}

par(mfrow=c(5,1))
for(k in 1:K){
  plot(fit_ebpmf$EF[,k],type='l')
}

par(mfrow=c(5,1))
for(k in 1:K){
  plot(fit_ebpmf$EF_smooth[,k],type='l')
}


for(k in 1:K){
  plot(fit_cluster_mix$phi[k,],type='l')
}

for(k in 1:K){
  plot(init$centers[k,],type='l')
}
```

