---
title: "Smoothed Matrix Factorization"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

## Overview 

Explore functional/smoothed matrix factorization(MF): consider the MF problem $Y = LF+E$, and assume $L$ is sparse and $F$ has smooth rows.

## Main Results

### EBMPMF

* [TPM3, stm fit example](tpm3_stm.html)

1. [Smoothed EBMF](SmoothMF.html): Wavelet Smoothing + EBMF
2. [Smoothed PMD](SmoothPMD.html): Wavelet Smoothing + PMD, compared with 1.
3. [Smoothed EBMF for Poisson data](SmoothMFpoisson2.html): Wavelet Smoothing + Transformation + EBMF
4. [EBMPMF](SmoothPMF.html), [EBMPMF2](SmoothPMF2.html): EBMPMF simple examples.
5. [Smoothed vs Non-smoothed](STMvsMLE.html): illustrate how smoothing could help when factors are indeed smooth.
6. [Sparse NMF methods](nmfsparse.html): Try some esixting sparse NMF methods.
7. [VST NMF](VSTNMF.html): does VST work well for NMF?
8. [EBMPMF and nugget effect](SmoothPMFnugget.html)
9. [Apply stm to gene splicing](stmGTEx.html): 1. looked at 3 genes and compared 6 methods. 2. large reads at the beginning/ending of exons may due to splitting reads.
10. [5 low expressed genes with 3 topics and structure plot](lowgene.html): compare NMF and stm-smashgen.
11. [The other 16 genes with 3 topics and structure plot](lowgene2.html)
12. [Fix F, update L using fastTopics](fixFupdateL_fastTopics.html)
13. [log transformed counts](log_transform_counts.html)
14. [a new likelihood expansionn](new_poisson_matrix_lik_expansion.html)

### Integration analysis on RNA, histone mark and ATAC seq data

1. [Initial analysis on luis data](luis_data.html)
2. [run wave ebmf on luis data](luis_data_wave.html)
3. [run stm on the data](integration_stm.html)
4. [Simulations on joint factor analysis](joint_factoranalysis.html)
5. [Another simulation illustrating diff bwt wave_flash and flash](joint_fa_more.html)

### PTF

1. [Trend Filtering](PoissonTrendFiltering.html)
2. [Trend filtering and dynamic linear model](trendfiltering.html)
3. [Examples](tfexample.html)
4. [Poisson Trend Filtering](ptfopt.html): first try of the ptf method, implemented optimization-based method to see if it works.
5. [Basis selection in TF](tforder.html)

### EBPM

1. [Empirical Bayes Poisson Mean large scale](poissonmeanscale.html)
2. [Compare ebpm estimate from different scales](ebpmscale.html)
3. [EBPM scale invariant version](poissonmean2.html): when $s$ is large, little shrinkage compared with MLE.
4. [EBPM mixture of two gamma distributions](poissonmean3.html): fix prior grid at truth.
5. [EBPM mixture of two gamma distributions](poissonmean4.html): closer priors make it harder to shrink.
6. [EBPM mixture of two gamma distributions](poissonmean5.html): same shape diff rate in priors.

## Mis

1. [Functional PCA](fpca.html)
2. [Summary of meeting on Aug 02](Meeting0802.html)
3. [Genome Annotation](GenomeAnnotation.html)
4. [EM algorithm for Topic Model](TopicModelEM.html)
5. [Analysis on Xing's method](XingMethod.html)
6. [command line and github tips](tips.html)
7. [Principal Curves](princurves.html)
8. [Outlier in wavelet smoothing](outlierWavelet.html)
9. [Robust smashgen](outlierSmashgen.html)
10. [Biwhitening](biwhitening.html)
11. [try MoMA](moma.html)
12. [Second derivatives of $\log f(x)$](bound_log_marginal.html)

## Dynamics

1. [normal-gamma autoregressive (NGAR) process](ngar.html)
2. [Dynamic spike and slab(dss) process prior](dss.html)

## Wavelet

1.[Fast calculate diag($WDW^T$)](wdw.html)
2.[the need to reflect data](reflect_data_wavelet.html)

## Normal mean penalty form

1. [bound on (log g)''](bound_log_marginal.html)
2. [log density of normal mixture](log_gmm_concave.html)
3. [log density of laplace mixture](log_lmm_concave.html)
4. [normal mean penalty plots](normal_mean_penalty.html)

## Ref

1. [Variational EM ppt](http://www.cs.cmu.edu/~tom/10-702/Zoubin-702.pdf), [Variational EM paper](http://mlg.eng.cam.ac.uk/zoubin/papers/valencia02.pdf)
2. [A Comparative Simulation Study of Wavelet Shrinkage Estimators for Poisson Counts](https://www.jstor.org/stable/pdf/1403855.pdf)
3. [Multiscale Topic Tomography](http://www.cs.cmu.edu/~wcohen/postscript/topic-tomography-submitted.pdf)
4. [Bayesian Multiscale Models for Poisson Processes](https://www.jstor.org/stable/pdf/2670007.pdf)

