---
title: "low expression gene"
author: "DongyueXie"
date: "2020-02-20"
output:
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r}
library(stm)
library(NNLM)


sum_base = function(x,base){
  x = x[1:(floor(length(x)/base)*base)]
  colSums(matrix(x,nrow=base))
}

#compare methods like nmf, stm-bmsm, stm-smashgen, stm-smashgen robust, HALS-wavelet, HALS-runmed

gene_splicing_study = function(X,name,K,nreps = 6,seed=12345,base=1,path){
  
  set.seed(seed)
  
  if(base>1){
    X = t(apply(X, 1, sum_base,base=base))
  }
  
  nmf_loss = Inf
  stm_loss = Inf
  stm_nugget_loss = Inf
  stm_nugget_robust_loss = Inf
  hals_wavelet_loss = Inf
  hals_runmed_loss = Inf
  
  for (reps in 1:nreps) {
    
    print(reps)
    
    fit_NMF = nnmf(X,k=K,method = 'scd',loss='mkl',verbose = F)
    if(min(fit_NMF$mkl)<nmf_loss){
      nmf_loss = min(fit_NMF$mkl)
      save(fit_NMF,file = paste(path,name,'_NMF_mkl_scd_K',K,'_base',base,'.RData',sep = ''))
    }
    
    fit_stm = stm(X,K,init = list(L_init=fit_NMF$W,F_init = fit_NMF$H),
                  return_all = FALSE,tol=1e-3,maxiter=50,printevery = 1e5)
    if(fit_stm$KL[length(fit_stm$KL)]<stm_loss){
      stm_loss=fit_stm$KL[length(fit_stm$KL)]
      save(fit_stm,file=paste(path,name,'_stm_bmsm_K',K,'_base',base,'.RData',sep = ''))
    }
    
    fit_stm_nugget_robust = stm(X,K,init = list(L_init=fit_NMF$W,F_init = fit_NMF$H),
                                return_all = FALSE,tol=1e-2,nugget = TRUE,maxiter=50,printevery = 1e5)
    if(fit_stm_nugget_robust$KL[length(fit_stm_nugget_robust$KL)]<stm_nugget_robust_loss){
      stm_nugget_robust_loss=fit_stm_nugget_robust$KL[length(fit_stm_nugget_robust$KL)]
      save(fit_stm_nugget_robust,file=paste(path,name,'_stm_nugget_robust_K',K,'_base',base,'.RData',sep = ''))
    }
    
    fit_stm_nugget = stm(X,K,init = list(L_init=fit_NMF$W,F_init = fit_NMF$H),
                         return_all = FALSE,tol=1e-2,nugget = TRUE,maxiter=50,printevery = 1e5,
                         nug_control_f = list(robust=F))
    if(fit_stm_nugget$KL[length(fit_stm_nugget$KL)]<stm_nugget_loss){
      stm_nugget_loss=fit_stm_nugget$KL[length(fit_stm_nugget$KL)]
      save(fit_stm_nugget,file=paste(path,name,'_stm_nugget_K',K,'_base',base,'.RData',sep = ''))
    }
    
    fit_hals_wavelet = NMF_HALS(X,K,smooth_method = 'wavelet',printevery = 1e5)
    if(fit_hals_wavelet$loss[length(fit_hals_wavelet$loss)]<hals_wavelet_loss){
      hals_wavelet_loss = fit_hals_wavelet$loss[length(fit_hals_wavelet$loss)]
      save(fit_hals_wavelet,file=paste(path,name,'_hals_wavelet_K',K,'_base',base,'.RData',sep = ''))
    }
    
    fit_hals_runmed = NMF_HALS(X,K,smooth_method = 'runmed',printevery = 1e5)
    
    if(fit_hals_runmed$loss[length(fit_hals_runmed$loss)]<hals_runmed_loss){
      hals_runmed_loss = fit_hals_runmed$loss[length(fit_hals_runmed$loss)]
      save(fit_hals_runmed,file=paste(path,name,'_hals_runmed_K',K,'_base',base,'.RData',sep = ''))
    }
  }
}

plot_factors3 = function(X,method){
  plot(X[,1],col=2,ylim=range(lf$FF),type='l',xlab = '',ylab='Intensity',main=paste('Factors - ',method,sep=''))
lines(X[,2],col=3)
lines(X[,3],col=4)
}
```

## Introduction

find genes with small 95% quantile of expression

```{r,eval=FALSE}
path = '/home/dyxie/NMF/YangLi/readcount'
count.files = list.files(path=path)
data.list = lapply(count.files,function(x){
  datax = read.table(paste(path,'/',x,sep='',collapse = ''),header = T)
  quantile(rowSums(datax[,-c(1:3)])/457,0.99)
  #mean(rowSums(datax[,-c(1:3)])/457)
})
gene.order = order(unlist(data.list),decreasing = F)
```

## per 10 base count sum

run models for top 5 genes with smallest expression.

### 20:57603732-57607422

```{r,fig.width=12,fig.height=5}
library(CountClust)
# K=3
# base=10
# path.save = '~/SMF/data/lowgene/'
# for(gene in gene.order[1:5]){
#   X = read.table(paste(path,'/',count.files[gene],sep='',collapse = ''),header = T)
#   X = t(X[,-c(1:3)])
#   gene_splicing_study(X,count.files[gene],K,base=base,path=path.save)
# }

#plot results, factors and structure plot.
#compare nmf, smashgen_nmf, hals_runmed
load("~/SMF/data/lowgene/Counts_20:57603732-57607422.txt.gz_NMF_mkl_scd_K3_base10.RData")
load("~/SMF/data/lowgene/Counts_20:57603732-57607422.txt.gz_stm_nugget_K3_base10.RData")

lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
plot_factors3(lf$FF,'NMF')
lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
plot_factors3(lf$FF,'smoothed')

```

```{r,fig.width=10,fig.height=10}
library(gridExtra)
lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
annotation = data.frame(sample_id=1:length(fit_NMF$label),tissue_label=fit_NMF$label)
a=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'NMF',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
b=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'smoothed',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))
grid.arrange(a, b, ncol=2)
```

### 10:73576054-73611082

```{r,fig.width=12,fig.height=5}
load("~/SMF/data/lowgene/Counts_10:73576054-73611082.txt.gz_NMF_mkl_scd_K3_base10.RData")
load("~/SMF/data/lowgene/Counts_10:73576054-73611082.txt.gz_stm_nugget_K3_base10.RData")

lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
plot_factors3(lf$FF,'NMF')
lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
plot_factors3(lf$FF,'smoothed')

```

```{r,fig.width=10,fig.height=10}
lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
annotation = data.frame(sample_id=1:length(fit_NMF$label),tissue_label=fit_NMF$label)
a=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'NMF',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
b=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'smoothed',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))
grid.arrange(a, b, ncol=2)
```

### 3:101399933-101405563

```{r,fig.width=12,fig.height=5}
load("~/SMF/data/lowgene/Counts_3:101399933-101405563.txt.gz_NMF_mkl_scd_K3_base10.RData")
load("~/SMF/data/lowgene/Counts_3:101399933-101405563.txt.gz_stm_nugget_K3_base10.RData")

lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
plot_factors3(lf$FF,'NMF')
lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
plot_factors3(lf$FF,'smoothed')

```

```{r,fig.width=10,fig.height=10}
lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
annotation = data.frame(sample_id=1:457,tissue_label=c(rep('Adipose',226),rep('Skin',231)))
a=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'NMF',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
b=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'smoothed',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))
grid.arrange(a, b, ncol=2)
```

### 6:44214694-44221625

```{r,fig.width=12,fig.height=5}
load("~/SMF/data/lowgene/Counts_6:44214694-44221625.txt.gz_NMF_mkl_scd_K3_base10.RData")
load("~/SMF/data/lowgene/Counts_6:44214694-44221625.txt.gz_stm_nugget_K3_base10.RData")

lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
plot_factors3(lf$FF,'NMF')
lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
plot_factors3(lf$FF,'smoothed')

```

```{r,fig.width=10,fig.height=10}
lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
annotation = data.frame(sample_id=1:457,tissue_label=c(rep('Adipose',226),rep('Skin',231)))
a=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'NMF',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
b=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'smoothed',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))
grid.arrange(a, b, ncol=2)
```



### 19:2269519-2273487

```{r,fig.width=12,fig.height=5}
load("~/SMF/data/lowgene/Counts_19:2269519-2273487.txt.gz_NMF_mkl_scd_K3_base10.RData")
load("~/SMF/data/lowgene/Counts_19:2269519-2273487.txt.gz_stm_nugget_K3_base10.RData")

lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
plot_factors3(lf$FF,'NMF')
lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
plot_factors3(lf$FF,'smoothed')

```

```{r,fig.width=10,fig.height=10}
lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
annotation = data.frame(sample_id=1:length(fit_NMF$label),tissue_label=fit_NMF$label)
a=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'NMF',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
b=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'smoothed',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))
grid.arrange(a, b, ncol=2)
```

