---
title: "low expression gene, continued"
author: "DongyueXie"
date: "2020-02-21"
output:
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

## per 10 base count sum

```{r,fig.width=10,fig.height=10}
library(stm)
plot_factors3 = function(X,method){
  plot(X[,1],col=2,ylim=range(lf$FF),type='l',xlab = '',ylab='Intensity',main=paste('Factors - ',method,sep=''))
lines(X[,2],col=3)
lines(X[,3],col=4)
}
library(CountClust)
library(gridExtra)
load('data/count_files.RData')
load('data/lowgene/gene_order_99_quantile.RData')
```

```{r,fig.width=10,fig.height=10}
path = 'data/lowgene/'
K=3
base=10
for(gene in count.files[gene.order[6:21]]){
  
  message(noquote('---------------------------------------------------------------------'))
message(noquote(paste('Plot of',gene,sep=' '))  )
  
  load(paste(path,gene,'_NMF_mkl_scd_K',K,'_base',base,'.RData',sep = ''))
  load(paste(path,gene,'_stm_nugget_K',K,'_base',base,'.RData',sep = ''))
  
  par(mfrow=c(2,1))
  lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
plot_factors3(lf$FF,'NMF')
lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
plot_factors3(lf$FF,'smoothed')

lf = poisson2multinom(t(fit_NMF$H),fit_NMF$W)
annotation = data.frame(sample_id=1:length(fit_NMF$label),tissue_label=fit_NMF$label)
a=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'NMF',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

lf = poisson2multinom(t(fit_stm_nugget$qf),fit_stm_nugget$ql)
b=StructureGGplot(lf$L,annotation,palette = c(2,3,4),order_sample = TRUE,figure_title = 'smoothed',
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))
grid.arrange(a, b, ncol=2)
}
```
