---
title: "Try MoMA package"
author: "Dongyue Xie"
date: "2022-04-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction


```{r}
library(MoMA)
```

Generate some data

```{r}
get.X <- function(n=50,p=200,snr=1) {
    #n <- 50
    #p <- 200
    K <- 3
    #snr <- 1

    ## Step 1: sample U, an orthogonal matrix
    rand_semdef_sym_mat <- crossprod(matrix(runif(n * n), n, n))
    rand_ortho_mat <- eigen(rand_semdef_sym_mat)$vector[, 1:K]
    u_1 <- rand_ortho_mat[, 1]
    u_2 <- rand_ortho_mat[, 2]
    u_3 <- rand_ortho_mat[, 3]

    ## Step 2: generate V, the signal
    set_zero_n_scale <- function(x, index_set) {
        x[index_set] <- 0
        x <- x / sqrt(sum(x^2))
        x
    }

    b_1 <- 7 / 20 * p
    b_2 <- 13 / 20 * p

    x <- as.vector(seq(p))

    # Sinusoidal signal
    v_1 <- sin((x + 15) * pi / 17)
    v_1 <- set_zero_n_scale(v_1, b_1:p)

    # Gaussian-modulated sinusoidal signal
    v_2 <- exp(-(x - 100)^2 / 650) * sin((x - 100) * 2 * pi / 21)
    v_2 <- set_zero_n_scale(v_2, c(1:b_1, b_2:p))

    # Sinusoidal signal
    v_3 <- sin((x - 40) * pi / 30)
    v_3 <- set_zero_n_scale(v_3, 1:b_2)

    ## Step 3, the noise
    eps <- matrix(rnorm(n * p), n, p)

    ## Step 4, put the pieces together
    X <- n / 3 * u_1 %*% t(v_1) +
        n / 5 * u_2 %*% t(v_2) +
        n / 6 * u_3 %*% t(v_3) +
        eps

    # Print the noise-to-signal ratio
    cat(paste("norm(X) / norm(noise) = ", norm(X) / norm(eps)))

    # Plot the signals
    yrange <- max(c(v_1, v_2, v_3))
    plot(v_1,
        type = "l",
        ylim = c(-yrange, yrange),
        ylab = "v", xlab = "i",
        main = "Plot of Signals"
    )
    lines(v_2, col = "blue")
    lines(v_3, col = "red")
    legend(0, 0.25,
        legend = expression(v[1], v[2], v[3]),
        lty = 1,
        col = c("black", "blue", "red"),
        cex = 0.6
    )

    return(list(X=X,L = cbind(u_1,u_2,u_3),FF=cbind(v_1,v_2,v_3)))
}
```


```{r}
set.seed(12345)
Y = get.X(n=100)
X = Y$X
```

```{r}
Omega_v <- second_diff_mat(200)
res <- moma_sfpca(X,
    center = FALSE,
    v_sparse = moma_lasso(lambda = 1),
    v_smooth = moma_smoothness(Omega_v, alpha = 2)
)
v_moma <- res$get_mat_by_index()$V
v_svd <- svd(X)$v[, 1]

par(mfrow = c(1, 2))
plot(v_moma,
    type = "l",
    ylab = expression(v[MoMA]),
    main = expression(paste(lambda[v] == 1, ", ", alpha[v] == 2))
)
plot(v_svd,
    type = "l",
    ylab = expression(v[SVD]),
    main = expression(paste(lambda[v] == 0, ", ", alpha[v] == 0))
)
```


```{r}
res <- moma_sfpca(X,
    center = FALSE,
    v_sparse = moma_lasso(lambda = seq(0, 3, length.out = 9)),
    v_smooth = moma_smoothness(Omega_v, alpha = 2),
    rank = 1
)

par(mfrow = c(3, 3))
for (i in 1:9) {
    res_i <- res$get_mat_by_index(lambda_v = i)
    plot(res_i$V,
        main = bquote(lambda[v] == .(res_i$chosen_lambda_v)),
        ylab = "v",
        type = "l"
    )
}
```

Nested BIC

```{r}
res <- moma_sfpca(
    X,
    center = FALSE,
    v_sparse = moma_lasso(
        lambda = seq(0, 3, length.out = 40),
        select_scheme = "b"
    ),
    v_smooth = moma_smoothness(Omega_v, alpha = 2)
)$get_mat_by_index()
```


```{r}
par(mfrow=c(1,1))
plot(res$V,
    ylab = "v",
    type = "l",
    main = bquote(lambda[v] == .(res$chosen_lambda_v))
)
```



### rank 3

BIC

```{r}
res <- moma_sfpca(
    X,
    center = FALSE,
    v_sparse = moma_lasso(
        lambda = seq(0, 3, length.out = 40),
        select_scheme = "b"
    ),
    v_smooth = moma_smoothness(Omega_v, 
                               alpha = seq(0, 3, length.out = 40),
                               select_scheme = "b"),
    rank = 3,
    deflation_scheme = "PCA_Schur_Complement"
)
```

```{r}
plot(res$get_mat_by_index()$V[,1],type='l')
plot(res$get_mat_by_index()$V[,2],type='l')
plot(res$get_mat_by_index()$V[,3],type='l')
```


grid search.

```{r}
res <- moma_sfpca(
    X,
    center = FALSE,
    v_sparse = moma_lasso(
        lambda = seq(0, 3, length.out = 6)
    ),
    v_smooth = moma_smoothness(Omega_v, alpha = seq(0, 3, length.out = 6)),
    rank = 3,
    deflation_scheme = "PCA_Schur_Complement"
)
```

```{r}
plot(res$get_mat_by_index()$V[,1],type='l')
plot(res$get_mat_by_index()$V[,2],type='l')
plot(res$get_mat_by_index()$V[,3],type='l')
```

Try flash

```{r}
library(flashr)
fit.flash = flash(X,var_type = 'constant')
plot(fit.flash$ldf$f[,1],type='l')
plot(fit.flash$ldf$f[,2],type='l')
#plot(fit.flash$ldf$f[,3],type='l')
```

Try funflash

```{r}
library(funflash)
datax = funflash_set_data(X,reflect.data = F,
                          type='wavelet',filter.number = 10,
                          family="DaubLeAsymm")
fit = funflash(datax,var.type = 'constant')
plot(fit$ldf$f[,1],type='l')
plot(fit$ldf$f[,2],type='l')
plot(fit$ldf$f[,3],type='l')
plot(fit$ldf$f[,4],type='l')
plot(fit$ldf$f[,5],type='l')
plot(fit$ldf$f[,6],type='l')
plot(fit$ldf$f[,7],type='l')
```

There are some redundant factors. Why?

```{r}
datax = funflash_set_data(X,reflect.data = T,
                          type='wavelet',filter.number = 10,
                          family="DaubLeAsymm")
fit = funflash(datax,Kmax = 3,var.type = 'constant')
plot(fit$ldf$f[,1],type='l')
plot(fit$ldf$f[,2],type='l')
plot(fit$ldf$f[,3],type='l')
```

```{r}
datax = funflash_set_data(X,reflect.data = T,
                          type='station',filter.number = 10,
                          family="DaubLeAsymm")
dim(datax$Y)
fit = funflash(datax,Kmax = 5,var.type = 'constant')
plot(fit$ldf$f[,1],type='l')
plot(fit$ldf$f[,2],type='l')
plot(fit$ldf$f[,3],type='l')
plot(fit$ldf$f[,4],type='l')
plot(fit$ldf$f[,5],type='l')
```


## Another example

```{r}
set.seed(12345)
n <- 50
p <- 256
K <- 3
snr <- 1

## Step 1: sample U, an orthogonal matrix
rand_semdef_sym_mat <- crossprod(matrix(runif(n * n), n, n))
rand_ortho_mat <- eigen(rand_semdef_sym_mat)$vector[, 1:K]
u_1 <- rand_ortho_mat[, 1]
u_2 <- rand_ortho_mat[, 2]
u_3 <- rand_ortho_mat[, 3]

f1 = c(rep(0,p/8), rep(1, p/4), rep(0, p/4), rep(0, p/4),rep(0,p/8))
f2 = c(rep(0,p/8), rep(0, p/4), rep(1, p/4), rep(0, p/4),rep(0,p/8))
f3 = c(rep(0,p/8), rep(0, p/4), rep(0, p/4), rep(1, p/4),rep(0,p/8))

L = cbind(u_1,u_2,u_3)
FF=cbind(f1,f2,f3)

plot(f1,type='l')
plot(f2,type='l')
plot(f3,type='l')

M = n / 3 * u_1 %*% t(f1) +
        n / 5 * u_2 %*% t(f2) +
        n / 6 * u_3 %*% t(f3)
v = var(c(M))/snr
X = M + matrix(rnorm(n*p,0,sqrt(v)),nrow=n,ncol=p)
```

```{r}
Omega_v <- second_diff_mat(p)
res <- moma_sfpca(
    X,
    center = FALSE,
    v_sparse = moma_lasso(
        lambda = seq(0, 3, length.out = 40),
        select_scheme = "b"
    ),
    v_smooth = moma_smoothness(Omega_v, 
                               alpha = seq(0, 3, length.out = 40),
                               select_scheme = "b"),
    rank = 3,
    deflation_scheme = "PCA_Schur_Complement"
)
```

```{r}
plot(res$get_mat_by_index()$V[,1],type='l')
plot(res$get_mat_by_index()$V[,2],type='l')
plot(res$get_mat_by_index()$V[,3],type='l')
```

```{r}
fit.flash = flash(X,var_type = 'constant')
plot(fit.flash$ldf$f[,1],type='l')
plot(fit.flash$ldf$f[,2],type='l')
plot(fit.flash$ldf$f[,3],type='l')
```

```{r}
datax = funflash_set_data(X,reflect.data = F,
                          type='wavelet',filter.number = 1,
                          family="DaubExPhase")
fit = funflash(datax,var.type = 'constant')
plot(fit$ldf$f[,1],type='l')
plot(fit$ldf$f[,2],type='l')
plot(fit$ldf$f[,3],type='l')
```

```{r}
datax = funflash_set_data(X,reflect.data = F,
                          type='wavelet',filter.number = 1,
                          family="DaubExPhase")
fit = funflash(datax,var.type = 'constant')
plot(fit$ldf$f[,1],type='l')
plot(fit$ldf$f[,2],type='l')
plot(fit$ldf$f[,3],type='l')
```

```{r}
datax = funflash_set_data(X,reflect.data = F,
                          type='station',filter.number = 1,
                          family="DaubExPhase")
fit = funflash(datax,var.type = 'constant',Kmax = 3)
plot(fit$ldf$f[,1],type='l')
plot(fit$ldf$f[,2],type='l')
plot(fit$ldf$f[,3],type='l')
```

```{r}
datax = funflash_set_data(X,reflect.data = F,
                          type='wavelet',filter.number = 1,
                          family="DaubExPhase")
fit = funflash(datax,var.type = 'zero',sigma2=v,Kmax = 3)
plot(fit$ldf$f[,1],type='l')
plot(fit$ldf$f[,2],type='l')
plot(fit$ldf$f[,3],type='l')
```

```{r}
source('code/smooth_flash.R')
fit = smooth_flash(X)
plot(fit$ldf$f[,1],type='l')
plot(fit$ldf$f[,2],type='l')
plot(fit$ldf$f[,3],type='l')
```

