---
title: "Poisson mean with large scale"
author: "Dongyue Xie"
date: "2019-11-07"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

In poisson mean model, $x\sim Poisson(s\lambda)$, when $s$ is large, the posterior mean is very close to $x/s$. Here is the example.

This is probably why we can not get sparsity in ebpmf. The scale is typically $300-500$ in ebpmf.



### $s=1$

```{r}
library(ebmpmf)
set.seed(12345)
pi0=0.8
lamda=c()
n=100
for(i in 1:100){
  idx = rbinom(1,1,pi0)
  if(idx){
    lamda[i] = rgamma(1,0.1,1)
  }else{
    lamda[i]=rgamma(1,10,2)
  }
}

x = rpois(n,lamda)

#x = seq(0,50)

fit = ebpm_exp_mixture(x,scale=c(0.01,100),shape=1,nullweight = 100)

fit$fitted_g

plot(x,fit$posterior$mean,xlab = 'MLE',ylab = 'Posterior mean',pch=16)
abline(0,1)

plot(x,col='grey80',pch=16)
lines(fit$posterior$mean,type='p',pch=3,col=2)
legend('topleft',c('MLE','Posterior mean'),col=c(1,2),pch=c(16,3))
```

### $s=100$

```{r}
s=100
x = rpois(n,s*lamda)

fit = ebpm_exp_mixture(x,s,scale=c(0.0001,10000),shape=1,nullweight = 1000)

fit$fitted_g

par(mfrow=c(1,2))

plot(x/s,fit$posterior$mean,xlab = 'MLE',ylab = 'Posterior mean',pch=16)
abline(0,1)

plot(x/s,col='grey80',pch=16)
lines(fit$posterior$mean,type='p',pch=3,col=2)
legend('topleft',c('MLE','Posterior mean'),col=c(1,2),pch=c(16,3))
```


If we treat $x/s$ as observation, then 

```{r}
fit = ebpm_exp_mixture(x/s,scale=c(0.01,100),shape=1)

par(mfrow=c(1,2))

plot(x/s,fit$posterior$mean,xlab = 'MLE',ylab = 'Posterior mean',pch=16)
abline(0,1)

plot(x/s,col='grey80',pch=16)
lines(fit$posterior$mean,type='p',pch=3,col=2)
legend('topright',c('MLE','Posterior mean'),col=c(1,2),pch=c(16,3))
```
