---
title: "Poisson Mean mixture of two Gammas"
author: "Dongyue Xie"
date: "2019-11-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
ebpm_gamma_mixture <- function(x,s = 1, shape=c(0.1,10),rate = c(1e3,1e-3), point_mass=F,
                             nullweight=1, weight = rep(1,length(x)),
                             g_init = NULL, fix_g = FALSE,
                             m = 2, control =  NULL, low = NULL,d=NULL){
  n=length(x)
  if(length(s) == 1){s = replicate(length(x),s)}
  if(is.null(control)){control = mixsqp_control_defaults()}
  if(is.null(g_init)){
    fix_g = FALSE ## then automatically unfix g if specified so
    rate = list(rate=rate,shape=shape)
    g_init = scale2gammamix_init(rate,point_mass)
  }
  
  if(!fix_g){ ## need to estimate g_init
    b = g_init$rate ##  from here use gamma(shape = a, rate = b)  where E = a/b
    a = g_init$shape
    tmp <-  compute_L(x,s,a, b,point_mass)
    L =  tmp$L
    l_rowmax = tmp$l_rowmax
    if(point_mass){x0 = c(g_init$pi0,g_init$pi)}else{x0 = g_init$pi}
    if(!is.null(nullweight)){
      Lnull = rbind(c(1,rep(0,ncol(L)-1)),L)
      weight = c(nullweight-1,weight)
      fit <- mixsqp(Lnull, weight,x0 = x0, control = control)
    }else{
      fit <- mixsqp(L, weight,x0 = x0, control = control)
    }
    pi = fit$x
    pi = pi/sum(pi) ## seems that some times pi does not sum to one
  }
  else{
    if(point_mass){
      pi = c(g_init$pi0,g_init$pi)
    }else{
      pi = g_init$pi
    }
    a = g_init$shape
    b = g_init$rate
    ## compute loglikelihood
    tmp <-  compute_L(x,s,a, b,point_mass)
    L =  tmp$L
    l_rowmax = tmp$l_rowmax
  }
  fitted_g = gammamix(pi = pi, shape = a,  rate  = b,point_mass)
  
  log_likelihood = sum(log(exp(l_rowmax) * L %*%  pi))
  
  cpm = outer(x,a,  "+")/outer(s, b, "+")
  if(point_mass){cpm = cbind(rep(0,n),cpm)}
  Pi_tilde = t(t(L) * pi)
  Pi_tilde = Pi_tilde/rowSums(Pi_tilde)
  lam_pm = rowSums(Pi_tilde * cpm)
  
  c_log_pm = digamma(outer(x,a,  "+")) - log(outer(s, b, "+"))
  if(point_mass){
    lam_log_pm = rowSums(Pi_tilde[,-1] * c_log_pm)
    lam_log_pm[x==0] = -Inf
  }else{
    lam_log_pm = rowSums(Pi_tilde * c_log_pm)
  }
  posterior = data.frame(mean = lam_pm, mean_log = lam_log_pm)
  return(list(fitted_g = fitted_g,
              posterior = posterior,
              log_likelihood = log_likelihood,
              Pi_tilde=Pi_tilde,
              tmp=tmp))
}


prune_fitted_g_ebpm = function(fitted_g,thresh=1e-10){
  rm_idx = which(fitted_g$pi<thresh)
  fitted_g$pi = fitted_g$pi[-rm_idx]
  fitted_g$shape = fitted_g$shape[-rm_idx]
  fitted_g$scale = fitted_g$scale[-rm_idx]
  fitted_g
}


## compute L matrix from data and selected grid
## L_ik = NB(x_i; a_k, b_k/b_k + s_i)
## but for computation in mixsqr, we can simplyfy it for numerical stability
compute_L <- function(x, s, a, b,point_mass){
  prob = 1 - s/outer(s,b, "+")
  l = dnbinom_cts_log(x,a,prob = prob) ##
  l_rowmax  = apply(l,1,max)
  if(point_mass){
    l0 = cbind(log(c(x==0)),l)
    L = exp(l0 -  l_rowmax)
  }else{
    L = exp(l -  l_rowmax)
  }
  
  return(list(L = L, l_rowmax = l_rowmax))
}


# it is equivalent to dnbinom in R wiht log = T when X is integer; I allow  it  to compute when x is not integer
dnbinom_cts_log <- function(x, a, prob){
  tmp = x*log(1-prob)
  tmp[x == 0] = 0 ## R says 0*-Inf = NaN
  out = t(t(log(prob)) * a) + tmp + lgamma(outer(x, a, "+")) - lgamma(x+1)
  out = t(t(out) - lgamma(a))
  return(out)
}

gammamix <- function(pi, shape, rate,point_mass) {
  if(point_mass){
    structure(list(pi = pi[-1], shape = shape, rate = rate, pi0 = pi[1]), class="gammamix")
  }else{
    structure(list(pi = pi, shape = shape, rate = rate), class="gammamix")
  }
}

scale2gammamix_init <- function(rate,point_mass){
  n = length(rate$shape) + point_mass
  pi_init = replicate(n, 1)/n
  return(gammamix(pi = pi_init, shape = rate$shape, rate =  rate$rate,point_mass))
}

mixsqp_control_defaults <- function() {
  return(list(verbose = F))
}

```

I tried the mixture of two gamma distributions. For now, we specify the true prior distribution.

```{r}
library(mixsqp)
set.seed(12345)
pi0=0.8
lamda=c()
n=100
for(i in 1:100){
  idx = rbinom(1,1,pi0)
  if(idx){
    lamda[i] = rgamma(1,0.1,1)
  }else{
    lamda[i]=rgamma(1,50,1)
  }
}

lamda = sort(lamda)

hist(lamda,breaks =20)

s=1
x = rpois(n,s*lamda)

fit = ebpm_gamma_mixture(x,s,shape = c(0.1,50), rate=c(1,1),nullweight = 20)

plot(x/s,fit$posterior$mean,xlab = 'MLE',ylab = 'Posterior mean',pch=16)
abline(0,1)

plot(x/s,col='grey80',pch=16)
lines(fit$posterior$mean,type='p',pch=3,col=2)
legend('topleft',c('MLE','Posterior mean'),col=c(1,2),pch=c(16,3))

fit$fitted_g
```

```{r}
tt = rbind((x/s)[70:80],
round((fit$posterior$mean)[70:80],3),round(exp(fit$posterior$mean_log),2)[70:80])
rownames(tt) = c('MLE',c('PosteriorMean','Exp(Elog)'))
colnames(tt) = 70:80
tt
```



```{r}
set.seed(12345)
s=100
x = rpois(n,s*lamda)

fit = ebpm_gamma_mixture(x,s,shape = c(0.1,50), rate=c(1,1),nullweight = 20)

plot(x/s,fit$posterior$mean,xlab = 'MLE',ylab = 'Posterior mean',pch=16)
abline(0,1)

plot(x/s,col='grey80',pch=16)
lines(fit$posterior$mean,type='p',pch=3,col=2)
legend('topleft',c('MLE','Posterior mean'),col=c(1,2),pch=c(16,3))

fit$fitted_g
```

```{r}
tt = rbind((x/s)[60:70],
round((fit$posterior$mean)[60:70],3),round(exp(fit$posterior$mean_log),2)[60:70])
rownames(tt) = c('MLE',c('PosteriorMean','Exp(Elog)'))
colnames(tt) = 60:70
tt
```
