---
title: "Poisson trend filtering"
author: "Dongyue Xie"
date: "2019-11-11"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Illustration on my new method for Poisson trend filtering. For simplicity, I only implemented 0-order one.

```{r}
#'@ lambda: tuning parameter
#'@ x: observed count seqeunce
ptf = function(x,lambda,niter=100,tol=1e-5){
  #initialize theta and beta_n
  n = length(x)
  #x[x==0] = 1e-8
  alpha = x[-n]/(x[-n]+x[-1])
  theta = log(alpha/(1-alpha))
  
  #theta=rep(0,n-1)
  
  beta_n = x[n]
  for(iter in 1:niter){
    theta_old = theta
    for(cd in 1:(n-1)){
      theta[cd] = update_thetai(x,lambda,cd,beta_n,theta)
    }
    beta_n = update_beta(x,theta)
    if(norm(theta-theta_old,'2')<=tol){
      break
    }
  }
  odds = exp(theta)
  beta_hat = rep(beta_n,n)
  for(i in (n-1):1){
    for(j in i:(n-1)){
      beta_hat[i] = beta_hat[i] * odds[j]
    }
  }
  return(list(beta=beta_hat,theta=theta))
}


update_thetai = function(x,lambda,i,beta_n,theta){
  
  n=length(x)
  
  sumexp = 0
  
  for(k in 1:i){
    sumtheta = 0
    for(j in k:(n-1)){
      if(j!=i){
        sumtheta = sumtheta + theta[j]
      }
    }
    sumexp = sumexp + exp(sumtheta)
  }
  
  if(i==(n-1)){
    sumexp = sumexp + 1
  }
  
  
  thresh = sum(x[1:i]) - beta_n*(sumexp)
  
  if(thresh<(-lambda)){
    thetai = log((lambda+sum(x[1:i]))/(beta_n*sumexp))
  }else if(thresh>lambda){
    thetai = log((sum(x[1:i])-lambda)/(beta_n*sumexp))
  }else{
    thetai = 0
  }
  
  thetai
  
}

update_beta = function(x,theta){
  beta_n = 0
  for(i in 1:(n-1)){
    sumtheta = 0
    for(j in i:(n-1)){
      sumtheta = sumtheta + theta[j]
    }
    beta_n = beta_n + exp(sumtheta)
  }
  beta_n = sum(x)/(1+beta_n)
}
```

## Step function

```{r}
library(smashr)
set.seed(123)
n=100
mu = c(rep(5,n/2),rep(10,n/2))
x = rpois(n,mu)

fit = ptf(x,lambda=11)
fit_smash = smash.poiss(x)

plot(x,col='grey80')
lines(mu,col='grey80')
lines(fit$beta)
lines(fit_smash,col=2)
legend('topleft',c('truth','ptf','smash'),lty=c(1,1,1),col=c('grey80',1,2))
```


```{r}
mu = c(rep(5,n/4),rep(8,n/4),rep(11,n/4),rep(6,n/4))
x = rpois(n,mu)
fit = ptf(x,13)
fit_smash = smash.poiss(x)

plot(x,col='grey80')
lines(mu,col='grey80')
lines(fit$beta)
lines(fit_smash,col=2)
legend('topleft',c('truth','ptf','smash'),lty=c(1,1,1),col=c('grey80',1,2))
```
