---
title: "wave flash structure different from flash"
author: "Dongyue Xie"
date: "2021-11-13"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Explore why there's different structure between waveflash and flash. Waveflash model is $YW = LFW + EW$.

```{r}
library(funflash)

set.seed(12345)
n <- 150
p <- 256
K <- 3
snr <- 1

## Step 1: sample U, an orthogonal matrix
#rand_semdef_sym_mat <- crossprod(matrix(runif(n * n), n, n))
#rand_ortho_mat <- eigen(rand_semdef_sym_mat)$vector[, 1:K]
# u_1 <- rand_ortho_mat[, 1]
# u_2 <- rand_ortho_mat[, 2]
# u_3 <- rand_ortho_mat[, 3]

L = matrix(0,nrow=n,ncol=K)
pi0=1/3
while(sum(rowSums(L)==0)>0){
  for(k in 1:K){
    l1 = c(rep(0,n*pi0),
           rnorm(n*(1-pi0)/2,0,sqrt(0.25)),
           rnorm(n*(1-pi0)/2,0,sqrt(1)))
    L[,k] =  l1[sample(1:n)]
  }
}

f0 = 0
f1 = c(rep(f0,p/8), rep(1, p/4), rep(f0, p/4), rep(f0, p/4),rep(f0,p/8))
f2 = c(rep(f0,p/8), rep(f0, p/4), rep(-1, p/4), rep(f0, p/4),rep(f0,p/8))
f3 = c(rep(f0,p/8), rep(f0, p/4), rep(f0, p/4), rep(1, p/4),rep(f0,p/8))

#f1 = c(rep(1,p/8), rep(5, p/4), rep(1, p/4), rep(1, p/4),rep(1,p/8))
#f2 = c(rep(1,p/8), rep(1, p/4), rep(-5, p/4), rep(1, p/4),rep(1,p/8))
#f3 = c(rep(1,p/8), rep(1, p/4), rep(1, p/4), rep(5, p/4),rep(1,p/8))

#L = cbind(u_1,u_2,u_3)
#L = matrix(rnorm(n*K),n,K)
FF=cbind(f1,f2,f3)

plot(f1,type='l')
plot(f2,type='l')
plot(f3,type='l')

M = tcrossprod(L,FF)
v = var(c(M))/snr
X = M + matrix(rnorm(n*p,0,sqrt(v)),nrow=n,ncol=p)
```

```{r}
library(flashr)
fit.flash = flash(X,var_type = 'constant',ebnm_fn = 'ebnm_pl')
plot(fit.flash$ldf$f[,1],type='l')
plot(fit.flash$ldf$f[,2],type='l')
plot(fit.flash$ldf$f[,3],type='l')
```

```{r}
datax = funflash_set_data(X,reflect.data = FALSE,type='wavelet')
fit.dwt = funflash(datax,var.type = 'constant',seed=123,ebnm_fn = 'ebnm_pl')
plot(fit.dwt$ldf$f[,1],type='l')
plot(fit.dwt$ldf$f[,2],type='l')
plot(fit.dwt$ldf$f[,3],type='l')
```

```{r}
datax = funflash_set_data(X,reflect.data = FALSE,type='station')
fit.ndwt = funflash(datax,var.type = 'constant',seed=123,Kmax=3,ebnm_fn = 'ebnm_pl')
plot(fit.ndwt$ldf$f[,1],type='l')
plot(fit.ndwt$ldf$f[,2],type='l')
plot(fit.ndwt$ldf$f[,3],type='l')
```

```{r}
fit.smooth_flash = smooth_flash(X,var_type='constant',ebnm_fn = 'ebnm_pl')
plot(fit.smooth_flash$ldf$f[,1],type='l')
plot(fit.smooth_flash$ldf$f[,2],type='l')
plot(fit.smooth_flash$ldf$f[,3],type='l')
```

## Another example

```{r}
library(funflash)

set.seed(12345)
n <- 150
p <- 256
K <- 3
snr <- 1

## Step 1: sample U, an orthogonal matrix
#rand_semdef_sym_mat <- crossprod(matrix(runif(n * n), n, n))
#rand_ortho_mat <- eigen(rand_semdef_sym_mat)$vector[, 1:K]
# u_1 <- rand_ortho_mat[, 1]
# u_2 <- rand_ortho_mat[, 2]
# u_3 <- rand_ortho_mat[, 3]

L = matrix(0,nrow=n,ncol=K)
pi0=1/3
while(sum(rowSums(L)==0)>0){
  for(k in 1:K){
    l1 = c(rep(0,n*pi0),
           rnorm(n*(1-pi0)/2,0,sqrt(0.25)),
           rnorm(n*(1-pi0)/2,0,sqrt(1)))
    L[,k] =  l1[sample(1:n)]
  }
}

f0 = 0.5
f1 = c(rep(f0,p/8), rep(1, p/4), rep(f0, p/4), rep(f0, p/4),rep(f0,p/8))
f2 = c(rep(f0,p/8), rep(f0, p/4), rep(-1, p/4), rep(f0, p/4),rep(f0,p/8))
f3 = c(rep(f0,p/8), rep(f0, p/4), rep(f0, p/4), rep(1, p/4),rep(f0,p/8))

#f1 = c(rep(1,p/8), rep(5, p/4), rep(1, p/4), rep(1, p/4),rep(1,p/8))
#f2 = c(rep(1,p/8), rep(1, p/4), rep(-5, p/4), rep(1, p/4),rep(1,p/8))
#f3 = c(rep(1,p/8), rep(1, p/4), rep(1, p/4), rep(5, p/4),rep(1,p/8))

#L = cbind(u_1,u_2,u_3)
#L = matrix(rnorm(n*K),n,K)
FF=cbind(f1,f2,f3)

plot(f1,type='l')
plot(f2,type='l')
plot(f3,type='l')

M = tcrossprod(L,FF)
v = var(c(M))/snr
X = M + matrix(rnorm(n*p,0,sqrt(v)),nrow=n,ncol=p)
```

```{r}
library(flashr)
fit.flash = flash(X,var_type = 'constant',ebnm_fn = 'ebnm_pl')
plot(fit.flash$ldf$f[,1],type='l')
plot(fit.flash$ldf$f[,2],type='l')
plot(fit.flash$ldf$f[,3],type='l')
```

```{r}
datax = funflash_set_data(X,reflect.data = FALSE,type='wavelet')
fit.dwt = funflash(datax,var.type = 'constant',seed=123,ebnm_fn = 'ebnm_pl')
plot(fit.dwt$ldf$f[,1],type='l')
plot(fit.dwt$ldf$f[,2],type='l')
plot(fit.dwt$ldf$f[,3],type='l')
```

```{r}
datax = funflash_set_data(X,reflect.data = FALSE,type='station')
fit.ndwt = funflash(datax,var.type = 'constant',seed=123,Kmax=3,ebnm_fn = 'ebnm_pl')
plot(fit.ndwt$ldf$f[,1],type='l')
plot(fit.ndwt$ldf$f[,2],type='l')
plot(fit.ndwt$ldf$f[,3],type='l')
```

```{r}
fit.smooth_flash = smooth_flash(X,var_type='constant',ebnm_fn = 'ebnm_pl')
plot(fit.smooth_flash$ldf$f[,1],type='l')
plot(fit.smooth_flash$ldf$f[,2],type='l')
plot(fit.smooth_flash$ldf$f[,3],type='l')
```








```{r,eval=FALSE}
n = 45
p = 256
K= 2

f0=0.5
FF = matrix(f0, nrow=p, ncol=3)
f1 = 5
f2 = 1
FF[(p/8*1):(p/8*2),1] = f1
FF[(p/8*3):(p/8*4),2] = f2
FF[(p/8*5):(p/8*7),3] = f1

FF2 = matrix(f0, nrow=p, ncol=3)
FF2[(p/8*1):(p/8*2),1] = f2
FF2[(p/8*3+10):(p/8*4-10),2] = f1
FF2[(p/8*5):(p/8*7),3] = f2

FFF = cbind(c(FF[,1],FF2[,3]),c(FF[,2],FF2[,2]),c(FF[,3],FF2[,1]))


for(k in 1:K){
  plot(FFF[,k],type='l',ylim = range(FFF),ylab='',xlab='')
}

set.seed(123)
L = matrix(0,nrow=n,ncol=K)
pi0=1/3
while(sum(rowSums(L)==0)>0){
  for(k in 1:K){
    l1 = c(rep(0,n*pi0),
           rnorm(n*(1-pi0)/2,0,sqrt(0.25)),
           rnorm(n*(1-pi0)/2,0,sqrt(1)))
    L[,k] =  l1[sample(1:n)]
  }
}

s = mean(apply(tcrossprod(L,FFF[,1:K]),1,sd))
X = tcrossprod(L,FFF[,1:K]) + matrix(rnorm(n*p*2,0,s),nrow=n,ncol=p*2)

datax = funflash_set_data(X,reflect.data = FALSE,type='station')
fit.dwt = funflash(datax,var.type = 'constant',Kmax=2,seed=123)
plot(fit.dwt$ldf$f[,1],type='l')
plot(fit.dwt$ldf$f[,2],type='l')

fit.flash = flash(X)
plot(fit.flash$ldf$f[,1],type='l')
plot(fit.flash$ldf$f[,2],type='l')

fit.smooth_flash = smooth_flash(X,var_type='constant')
plot(fit.smooth_flash$ldf$f[,1],type='l')
plot(fit.smooth_flash$ldf$f[,2],type='l')
```
